# Generated by Django 2.2.6 on 2019-11-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buycar',
            name='car_user',
            field=models.CharField(max_length=32),
        ),
    ]
