# Generated by Django 2.2.6 on 2019-11-04 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quser', '0004_quser_identity'),
        ('buyer', '0002_auto_20191104_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=32)),
                ('order_time', models.DateTimeField(auto_now=True)),
                ('order_number', models.IntegerField()),
                ('order_total', models.CharField(default=0, max_length=32)),
                ('order_state', models.IntegerField(default=0)),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quser.Quser')),
            ],
        ),
        migrations.CreateModel(
            name='Order_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=32)),
                ('goods_number', models.IntegerField()),
                ('goods_total', models.FloatField(default=0)),
                ('goods_price', models.FloatField()),
                ('goods_picture', models.CharField(max_length=32)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Pay_order')),
                ('order_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quser.Quser')),
            ],
        ),
    ]
