# Generated by Django 2.2.6 on 2019-11-04 09:23

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Quser', '0004_quser_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('picture', models.ImageField(default='shop/img/1.jpg', upload_to='shop/img')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('number', models.IntegerField()),
                ('production', models.DateTimeField()),
                ('safe_date', models.CharField(max_length=21)),
                ('picture', models.ImageField(default='shop/img/0.jpg', upload_to='shop/img')),
                ('description', ckeditor.fields.RichTextField()),
                ('statue', models.IntegerField()),
                ('goods_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quser.Quser')),
                ('goods_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Shop.GoodsType')),
            ],
        ),
    ]
