# Generated by Django 2.2.6 on 2019-10-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quser', '0002_auto_20191024_1520'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Quser',
        ),
    ]
