# Generated by Django 2.2.6 on 2019-11-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quser', '0003_auto_20191024_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='quser',
            name='identity',
            field=models.IntegerField(default=0),
        ),
    ]
